# Playbook to setup workstation inventory dynamic entry and launch site-osp-instances.yml 

- hosts: localhost
  tasks:
  - name: Create workstation inventory
    add_host:
       name: "workstation-{{OSP_GUID}}.rhpds.opentlc.com"
       group: workstation


- import_playbook: site-osp-instances.yml 

